### ISSUE TITLE
#include <util/delay_basic.h> not working with Arduino Due

### ISSUE THREAD

**Issue by shubham2711** [risitt/kissStepper#11]
Hi Sir,
I am trying to interface kissStepper library file with Arduino Due but it gives a fatal error: util/delay_basic.h: No such file or directory

 #include <util/delay_basic.h>

what should i do?
Is util.delay_basic only works with Atmega?? here i am using ARM based controller

**Comment by risitt** [comment]
Sorry to say, yes, this is an incompatibility with ARM (according to some web searched). I don't have any ARM hardware to test on, but I plan to in the future and will see if I can fix this.

Odd that there are such incompatibilities within the Arduino ecosystem...

**Comment by risitt** [comment]
My Arduino Due arrived yesterday so that I could test some changes I made to add compatibility with the Due. All seems to work well! Thanks for reporting the problem.
